<a href="https://colab.research.google.com/github/Prasunsk/ML_Assignments_Lectures/blob/master/Lecture_1_StudentGettingStarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Getting Started**






---

#Part1: numpy

---





---


**1. Importing the module**


---



In [0]:
import numpy as np



---
**2. Creating an array**
*


---




In [0]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [0]:
b = np.array( [ [1,2], [3,4] ], dtype=complex )
print(b)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [0]:
#create an array which contains zeros
c = np.zeros((2,3))
print('c = {}'.format(c))

c = [[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
# create an array of ones
d = np.ones((2,3,4), dtype=np.int16 )
print('d = {}'.format(d))

d = [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [0]:
# create an empty array
e = np.empty((3,3))
print('e = {}'.format(e))

e = [[2.71885036e-316 2.07507571e-322 2.12199579e-314]
 [3.44620186e-085 4.34900767e+199 1.87422380e+261]
 [1.43622020e+161 3.27748089e+180 1.27014396e-319]]


In [0]:
# create an identity array
f = np.eye(3)
print('f = {}'.format(f))

f = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
# create an array of ones with the same size of array c
g = np.ones_like(c)
print('g = {}'.format(g))

g = [[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
# create an array filled with inf values
h = np.full((3, 2), np.inf)
print('h = {}'.format(h))

h = [[inf inf]
 [inf inf]
 [inf inf]]


In [0]:
# create a 3*3 array
i = np.array([[0,1,2],[3,4,5],[6,7,8]])
print('i = {}'.format(i))

i = [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
# find the diagonal of the previous array
j = np.diag(i)
print('j = {}'.format(j))

j = [0 4 8]


In [0]:
# find the diagonals above and below the main diagonal
j = np.diag(i,k = 1)
print('j = {}'.format(j))
print("-"*20)
j = np.diag(i,k = -1) 
print('j = {}'.format(j))


j = [1 5]
--------------------
j = [3 7]




---
**3. Create a sequence of numbers**


---




In [0]:
# create a sequence of three numbers between 1 and 7
f = np.arange(1,7,2)
print("f = {}".format(f)) 

f = [1 3 5]


In [0]:
# create a sequence of numbers between 1 and 7 with stride 0.5
g = np.arange(1,7,0.5)
print("g = {}".format(g))

g = [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]


In [0]:
# create 10 numbers between 1 and 7
h = np.linspace(1,7,10)
print("h = {}".format(h)) 

h = [1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.         5.66666667 6.33333333 7.        ]




---
**Reshape an array**

---




In [2]:
# create a vector of 10 elements and reshape it into 5*2 array
a = np.arange(10)
print("a = {}".format(a))
print("-"*20)
b = a.reshape(5,2)
print("b = {}".format(b))

a = [0 1 2 3 4 5 6 7 8 9]
--------------------
b = [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
# flatten the previous array 
c = b.flatten()
print("c = {}".format(c))
c.shape

c = [0 1 2 3 4 5 6 7 8 9]


(10,)

In [4]:
# create a 2*3 array then find its transpose
d= np.array([[1,2,3],[4,5,6]])
print("d = {}".format(d))
print("-"*20)
e= d.transpose()
print("e = {}".format(e))

d = [[1 2 3]
 [4 5 6]]
--------------------
e = [[1 4]
 [2 5]
 [3 6]]


In [5]:
# create a random 3*2 array 
a = np.random.random_sample((3, 2)) *5
print("a = {}".format(a))

a = [[2.21396112 3.73139287]
 [2.40806534 2.63328647]
 [1.1921688  0.74174343]]


In [6]:
# find the minimum of the previous array (a) and its index
print("min(a) = {}".format(np.min(a)))
print("argmin(a) = {}".format(np.argmin(a)))

min(a) = 0.7417434333241762
argmin(a) = 5


In [7]:
# find the maximum of a and its index
print("max(a) = {}".format(np.max(a)))
print("argmax(a) = {}".format(np.argmax(a)))

max(a) = 3.7313928682245203
argmax(a) = 1


In [8]:
# find the maximums and minimums of rows 1,2
# np.maximum(x1,x2) is same as np.where(x1 >= x2, x1, x2) 
print("maximum of row1, row2 = {}".format(np.maximum(a[1],a[2])))
print("minimum of row1, row2 = {}".format(np.minimum(a[1],a[2])))

maximum of row1, row2 = [2.40806534 2.63328647]
minimum of row1, row2 = [1.1921688  0.74174343]




---

**Statistical measures**

---



In [9]:
# generate a random 3*2 array and compute its mean, variance, and standard deviation
a = np.random.random_sample((3, 2)) *5
print("a = {}".format(a))
print("-"*20)
print("mean(a) = {}".format(np.mean(a)))
print("var(a) = {}".format(np.var(a)))
print("std(a) = {}".format(np.std(a)))


a = [[2.274196   3.08885853]
 [1.02877117 4.44331603]
 [2.19043846 2.88551083]]
--------------------
mean(a) = 2.6518485031596097
var(a) = 1.0741387397770648
std(a) = 1.0364066478834766




---

**Linear Algebra**

---



In [10]:
# create a square, random matrix a 
a = np.random.random_sample((3, 3))
b = np.exp(a)
print("b = exp(a){}".format(b))

b = exp(a)[[1.76420472 1.33600673 1.70750488]
 [1.17284586 1.37649214 1.00810835]
 [1.01316112 1.10835586 1.8622168 ]]


In [11]:
# compute the determinant, rank, and trace of b
det = np.linalg.det(b)
print("determinant(b)= {}".format(det))
rank = np.linalg.matrix_rank(b)
print("rank(b)= {}".format(rank))
trace = np.trace(b)
print("trace(b)= {}".format(trace))

determinant(b)= 0.8359512510886243
rank(b)= 3
trace(b)= 5.0029136659572915


In [0]:
#find the eigen values and the eigen vectors of matrix b
eigen_val,eigen_vec = np.linalg.eig(b)
print("the eigen values of b:\n{}".format(eigen_val))
print("the the right eigen vectors of b:\n{}".format(eigen_vec))

In [12]:
# implement singular value decomposition on matrix b
u,s,vh = np.linalg.svd(b)
print("U of b is :\n{}".format(u))
print("V of b is :\n{}".format(vh))
print("singular values of b are :\n{}".format(s))

U of b is :
[[-0.66828495  0.18026899  0.72173285]
 [-0.48620481  0.62845127 -0.60716875]
 [-0.56302762 -0.75667172 -0.33233687]]
V of b is :
[[-0.5570448  -0.52497485 -0.64350796]
 [ 0.47208617  0.43732708 -0.76542777]
 [ 0.68325379 -0.73016877  0.00422259]]
singular values of b are :
[4.16424757 0.61106959 0.32851389]


In [3]:
# generate two arrays and compute their dot product
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
c = np.dot(a,b)
print("the dot product of a and b is:\n{}".format(c))
d = np.matmul(a,b)
print("the dot product of a and b is:\n{}".format(d))
print("the dot product of a and b is:\n{}".format(a*b))

the dot product of a and b is:
[[37 40]
 [85 92]]
the dot product of a and b is:
[[37 40]
 [85 92]]
the dot product of a and b is:
[[11 24]
 [39 56]]


In [3]:
# Generate an array and compute its inverse and its pseudo inverse
a = np.random.random_sample((3,3))
print(a)
# Compute the (multiplicative) inverse of a matrix.
print("the inverse of a is:")
b = np.linalg.inv(a)
print(b)
#compute the (Moore-Penrose) pseudo-inverse of a
print("the pseudo-inverse of a is:")
c = np.linalg.pinv(a)
print(c)

import random
np.random.seed(3)
d = random.randint(1, 10)  
print(d)
print(d)
np.random.seed(1099)
d = random.randint(1, 10) 
print(d)
print(d)



[[0.32854567 0.80838517 0.75673645]
 [0.13272404 0.52208127 0.97391064]
 [0.24627757 0.99200544 0.72761935]]
the inverse of a is:
[[ 7.87452148 -2.18257534 -5.26828224]
 [-1.9245425  -0.70772151  2.94883439]
 [-0.04145214  1.70361458 -0.86281379]]
the pseudo-inverse of a is:
[[ 7.87452148 -2.18257534 -5.26828224]
 [-1.9245425  -0.70772151  2.94883439]
 [-0.04145214  1.70361458 -0.86281379]]
10
10
3
3




---


#Part2: pandas


---





---

**1. Load the pandas package**

---



In [0]:
import pandas as pd



---



**2.   I want to store customers data. For a number of customers I know, the name(characters), age(integers), and sex(male/female) data.**


---





In [7]:
df = pd.DataFrame({
    "Name": ["Sahar",
             "Nisha",
             "Lokesh"],
    "Age":[28, 30, 25],
    "Sex":["female","female","male"]
})

df

Name  Age     Sex
0   Sahar   28  female
1   Nisha   30  female
2  Lokesh   25    male



---


**Note that:** A DataFrame is a 2-dimensional data structure that can store data of different types (including characters, integers,floating point values, categorical data and more) in columns.


---





---


**3.   To access the data of one column:**


---





In [8]:
df["Age"]

0    28
1    30
2    25
Name: Age, dtype: int64



---


**4. To know the maximum age of the customers:**


---



In [9]:
df["Age"].max()

30



---


**5. If you are interested of some basic statistics of the numerical data of your table try describe() method, which provides a quick overview of the numerical data in a DataFrame**


---



In [10]:
df.describe()

Age
count   3.000000
mean   27.666667
std     2.516611
min    25.000000
25%    26.500000
50%    28.000000
75%    29.000000
max    30.000000



---


**6. Dealing with CSV files**
pandas provides the read_csv() function to read data stored as a csv file into a pandas DataFrame


---



In [11]:
CustomerData = pd.read_csv("/content/drive/My Drive/CusomerData .csv") 

FileNotFoundError: ignored

In [0]:
# CustomerData



---


**To see the first two rows :**


---



In [0]:
CustomerData.head(2)



---


**A check on how pandas interpreted each of the column data types can be done by requesting the pandas dtypes
attribut**


---



In [0]:
# CustomerData.dtypes



---


**To store the data in an excel file:**


---



In [0]:
# CustomerData.to_excel('CustomerData.xlsx', sheet_name='Customers', index=False)

In [0]:
# CD = pd.read_excel('CustomerData.xlsx', sheet_name='Customers')
CD




---


**To get a technical summary of a DataFrame**


---



In [0]:
# CustomerData.info()



---



**Now let us select one column and look at its type and shape**


---



In [0]:
# sex = CustomerData["Gender"]
# # sex.head()

In [0]:
# sex.shape



---


**To select multiple columns:**


---



In [0]:
# CustomerData[["Gender","Name"]]



---


**To filter specific rows from a DataFrame:** 
pass the customer who are elder than 29


---



In [0]:
# above_29 = CustomerData[CustomerData["Age"]>29]
# above_29.head()




---


**How to select specific rows and columns from a DataFrame**


---



In [0]:
# names_above_29 = CustomerData.loc[CustomerData["Age"]>29,"Name"]
# names_above_29.head()




---


**Select rows from 1 to 3 and columns 1,2:**


---



In [0]:
# CustomerData.iloc[0:3,0:2]



---


**Note:**
1. Select specific rows and/or columns using loc when using the row and column names
2. Select specific rows and/or columns using iloc when using the positions in the table


---





---

**Plotting**

---



In [0]:
# import matplotlib.pyplot as plt

In [0]:
# CustomerData.plot()




---


**To plot only the columns of the data table with the data from Age**


---



In [0]:
# CustomerData["Age"].plot()

In [0]:
# CustomerData.plot.scatter(x="Id",
#                           y="Age")

In [0]:
# CustomerData.plot.box()



---


**Some Statistics**


---



In [0]:
# CustomerData["Age"].mean()

In [0]:
# CustomerData["Age"].median()

In [0]:
# CustomerData["Age"].max()

In [0]:
# CustomerData["Age"].min()

In [0]:
# CustomerData["Age"].skew()

In [0]:
# CustomerData["Age"].var()

In [0]:
# CustomerData["Age"].std()

In [0]:
# CustomerData["Age"].mode()



---


**Combining overlapping data sets**


---



In [0]:
# import numpy as np

In [0]:
# df1 = pd.DataFrame({'A': [1., np.nan, 3., 5., np.nan],
#                     'B': [np.nan, 2., 3., np.nan, 6.]})
# df2 = pd.DataFrame({'A': [5., 2., 4., np.nan, 3., 7.],
#                     'B': [np.nan, np.nan, 3., 4., 6., 8.]})


In [0]:
# df1

In [0]:
# df2

In [0]:
# df1.combine_first(df2)



---


**combine_first() combines two DataFrame objects where missing values in one 
DataFrame are conditionally filled with like-labeled values from the other DataFrame.**


---



In [0]:
# def combiner(x, y):
#   return np.where(pd.isna(x), y, x)

In [0]:
# df1 = pd.DataFrame({'A': [1., 2., 3., 5., 6.],
#                     'B': [1., np.nan, 3., 4., np.nan]})
# df2 = pd.DataFrame({'A': [5., 2., 4., 2., 3.],
#                     'B': [7., 3., 4., 6., 8.]})

# df3 = combiner(df1,df2)
# df3




---


**To exclude missing data you can use skipna = True**


---



In [0]:
# df1.sum(axis=1, skipna=True)



---


**Crosstabs**


---



In [0]:
# raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
#         'company': ['infantry', 'infantry', 'cavalry', 'cavalry', 'infantry', 'infantry', 'cavalry', 'cavalry','infantry', 'infantry', 'cavalry', 'cavalry'], 
#         'experience': ['veteran', 'rookie', 'veteran', 'rookie', 'veteran', 'rookie', 'veteran', 'rookie','veteran', 'rookie', 'veteran', 'rookie'],
#         'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
#         'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
#         'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}
# df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'experience', 'name', 'preTestScore', 'postTestScore'])
# df




---


**Counting the number of observations by regiment and category**


---



In [0]:
# pd.crosstab(df.regiment, df.company, margins=True)



---


**Create a crosstab of the number of rookie and veteran cavalry and infantry soldiers per regiment**


---



In [0]:
# pd.crosstab([df.company, df.experience], df.regiment,  margins=True)



---


**get_dummies()**
This function is used to convert categorical variable into dummy variable (one-hot encoding)


---



In [0]:
# List = list('Hello World')
# pd.get_dummies(List)

In [0]:
# pd.get_dummies(pd.Series(list('abc')), drop_first=True)

In [0]:
# pd.get_dummies(pd.Series(list('abc')), dtype = float)




---


**pd.DataFrame()**:
converts a numpy array into a data frame


---



In [0]:
# Array = np.array([[1,2,3],[4,5,6]])
# df1 =pd.DataFrame(Array) 
# df1



---


**you can use this function to get a numpy array as well**


---



In [0]:
# pd.DataFrame({"A": [1, 2,3], "B": [4,5,6]}).to_numpy()

In [12]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
!pwd

/content


In [0]:
!cd /content/drive
!ls

/bin/bash: line 0: cd: /content/drive: No such file or directory
sample_data
